package nasa.daidalus;

public enum BandType {
    HEADING, 
    GROUND_SPEED, 
    ALTITUDE, 
    VERTICAL_SPEED,
    RECOVERY_HEADING,
    RECOVERY_GROUND_SPEED,
    RECOVERY_ALTITUDE,
    RECOVERY_VERTICAL_SPEED
}